### ISSUE TITLE
Package development

### ISSUE THREAD

**Issue by friendly** [friendly/matlib#11]
John & I discussed some issues relating to development of the package toward a next release:
- _Naming conventions_: At present, we use a mix of camelCase (`gaussianElimination`, `showEqn`, ...) and underscored_names (`power_method`).  We should move toward a common standard, e.g., `power_method -> powerMethod`.  This should probably apply to file names also:  e.g., `gaussianElimination()` is in `gaussian-elimination.R`.
- There are a few functions that are redundant  (e.g, `echelon` is a call to `gaussianElimination`) or synonyms (`inv` is a call to `Inverse`), but where they serve a semantic purpose, we should allow this limited use.
- Where we supersede a standard function in R, we should use a consistent convention, e.g., an initial upper case letter, unless the function name is an acronym.  Thus, `qr()` -> `QR()`, and `svd()` -> `SVD()` are OK, but `eigen()` should be renamed `Eigen()`, rather than `eig()`.
- This points to the usefulness of a `Det()` function that would extend `det()` with a `verbose` argument.
- We should use our **own** functions consistently in other functions.

**Comment by philchalmers** [comment]
> Naming conventions: At present, we use a mix of camelCase (gaussianElimination, showEqn, ...) and underscored_names (power_method). We should move toward a common standard, e.g., power_method -> powerMethod. This should probably apply to file names also: e.g., gaussianElimination() is in gaussian-elimination.R.

Agreed. Though this is a bit conflicting (from the point below) with some other functions which mask the base R ones (e.g., `Eigen` versus `eigen`). Perhaps major/complex operations should begin with a capital, while minor operations begin with a lower case as well. So `GaussianElimination()`, `PowerMethod()`, `Vandermode()`,  `Proj()`, while things like `rowadd()`, `corner()`, `arc()`, etc are relatively minor and have lower cases. 

I think it's good to make a list of functions that need changing because there's lots of conflicting ways to do this. 

> There are a few functions that are redundant (e.g, echelon is a call to gaussianElimination) or synonyms (inv is a call to Inverse), but where they serve a semantic purpose, we should allow this limited use.

True, though `echelon` could gain a `reduced = FALSE` argument to distinguish between row echelon and reduced row echelon form. So it could still be included for completeness.  

> This points to the usefulness of a Det() function that would extend det() with a verbose argument.

I like this, especially if some plots were to accompany the method to show the area/volume interpretation for 2 (base graphics) and 3 variable systems (rgl). Though what would the `verbose` argument be for? To show the product of eigen values or something?

**Comment by friendly** [comment]
Re: `det()` and `Det`:  I suppose `Det(..., verbose=TRUE)` could at least show the cumulative product of the pivots, but this would depend on how it is implemented.

The vignette `"det-ex2"` already has examples showing the 2D area interpretation.  It is not hard conceptually to do this for 3D: take a unit cube and transform it by the matrix `A`.  Below is a start, but I don't know how to make it pretty.

```
library(rgl)
library(matlib)
cube <- cube3d()
c3d <- cube3d(color=palette(), alpha=0.1)

open3d()
shade3d(c3d)

vectors3d(
    rbind( diag(3), -diag(3) ),
    labels = c("X", "Y", "Z", rep(" ", 3)),
    frac.lab =1.1,
    headlength = 0.1, radius=1/30
    )

A <- matrix(c( 1,2,5, 3, 4, 1,  1,3,2), 3, 3)

shade3d(
        transform3d(c3d, A)
    )
```

**Comment by philchalmers** [comment]
Neat, thanks. I guess I was thinking of something with the same x-y(-z) axis range, like the image below, but in 3D. I recall Duncan allowed for multiple rgl plots to be done side-by-side, though I've never actually done it (my experience with `rgl` is pretty limited). 

![vp9nv](https://cloud.githubusercontent.com/assets/1274464/18810853/4eba826e-826e-11e6-84f3-eeeae812cd49.png)

Now, if only we could render a 3D sheep......

**Comment by friendly** [comment]
How about a 3D horse? This one is pretty awesome.
https://www.youtube.com/watch?v=YncZtLaZ6kQ

**Comment by philchalmers** [comment]
I like it! Though I think we may get some flack from the SPCA if we start talking about shearing horses... :wink:

**Comment by john-d-fox** [comment]
I've done some renaming for consistency. Also, I added code to gaussianElimination() to compute determinants, and a Det() function to compute determinants by elimination, eigenvalues (for symmetric case), or expansion by minors and cofactors (making the last indirectly recursive).

**Comment by friendly** [comment]
That looks very good.  It looks like you did a thorough job of resolving the name changes in all files.

For `Det()`: would it make sense to add a `verbose` argument?  For `method=="eigenvalues"`, this would just `cat` the eigenvalues; for `method=="cofactors"` this would `cat` the cofactors of row 1.

**Comment by john-d-fox** [comment]
> -----Original Message-----
> From: Michael Friendly [mailto:notifications@github.com]
> Sent: October 4, 2016 5:23 PM
> To: friendly/matlib matlib@noreply.github.com
> Cc: Fox, John jfox@mcmaster.ca; Assign assign@noreply.github.com
> Subject: Re: [friendly/matlib] Package development (#11)
> 
> That looks very good. It looks like you did a thorough job of resolving the name
> changes in all files.
> 
> For Det(): would it make sense to add a verbose argument? For
> method=="eigenvalues", this would just cat the eigenvalues; for
> method=="cofactors" this would cat the cofactors of row 1.

I thought a bit about this after I committed the changes today but ran out of gas. It should be possible for method="elimination" too. Currently, gaussianElimination() saves a "det" attribute, but it could also save a vector of pivots and a count of row-interchanges. You'll see that I introduced an "enhancedMatrix" class, inheriting from "matrix", with a print() method that strips off attributes.

**Comment by john-d-fox** [comment]
> -----Original Message-----
> From: Michael Friendly [mailto:notifications@github.com]
> Sent: October 4, 2016 5:23 PM
> To: friendly/matlib matlib@noreply.github.com
> Cc: Fox, John jfox@mcmaster.ca; Assign assign@noreply.github.com
> Subject: Re: [friendly/matlib] Package development (#11)
> 
> That looks very good. It looks like you did a thorough job of resolving the name
> changes in all files.
> 
> For Det(): would it make sense to add a verbose argument? For
> method=="eigenvalues", this would just cat the eigenvalues; for
> method=="cofactors" this would cat the cofactors of row 1.

I added fractions and verbose args to Det(), but implemented them only for method = "elimination" and "eigenvalues". The reason I didn't do it for method = "cofactors" is that I think it would be more informative to show what's happening recursively, which will require some work.

**Comment by friendly** [comment]
For `method=="cofactors"`, I think it is sufficient to display the cofactors of the elements in the chosen row of the expansion, and not worry about the recursive bit.  `rowCofactors` uses `cofactor` in a loop.

**Comment by john-d-fox** [comment]
> -----Original Message-----
> From: Michael Friendly [mailto:notifications@github.com]
> Sent: October 5, 2016 8:37 AM
> To: friendly/matlib matlib@noreply.github.com
> Cc: Fox, John jfox@mcmaster.ca; Assign assign@noreply.github.com
> Subject: Re: [friendly/matlib] Package development (#11)
> 
> For method=="cofactors", I think it is sufficient to display the cofactors of the
> elements in the chosen row of the expansion, and not worry about the
> recursive bit. rowCofactors uses cofactor in a loop.

The interesting indirect recursion is that Det() calls rowCofactors(), which calls cofactor(), which calls minor(), which calls Det().
