### ISSUE TITLE
requireNamespace versus import

### ISSUE THREAD

**Issue by philchalmers** [friendly/matlib#13]
Is there a good reason to be using

``` r
mass <- requireNamespace("MASS", quietly=TRUE)
if (!mass) stop("fractions=TRUE needs MASS package")
fraction <- MASS::fractions
frac <- function(x) as.character(fraction(x))
```

instead of just importing `MASS::fraction`? I was thinking of making a more generic rounding/formatting function to clean up some clutter, but the presence of blocks like this seems a bit strange to me.

**Comment by friendly** [comment]
This is probably a holdover from an earlier way of doing things,  Should be cleaned up.
