### ISSUE TITLE
GramSchmidt

### ISSUE THREAD

**Issue by friendly** [friendly/matlib#16]
There has been a function `gsorth()` in the package, that was copied from `heplots` for Gram Schmidt orthogonalization, but that is intended for a data frame, and doesn't do what is transparent as GS for a matrix.

I just added the function `GramSchmidt()` that @philchalmers wrote a while ago.  Perhaps it could use a `verbose` argument.

If this is OK, I will deprecate and/or remove `gsorth`.

**Comment by philchalmers** [comment]
Or better yet, a [plot method](https://upload.wikimedia.org/wikipedia/commons/e/ee/Gram-Schmidt_orthonormalization_process.gif)? I'm okay with removing `gsorth` entirely.

**Comment by john-d-fox** [comment]
P {margin-top:0;margin-bottom:0;}



Hi,

I'm OK with this too.

John

-----------------------------
John Fox, Professor
McMaster University
Hamilton, Ontario
Canada L8S 4M4
web: socserv.mcmaster.ca/jfox
