### ISSUE TITLE
matlib package cannot open in MacOS

### ISSUE THREAD

**Issue by wuy3814** [friendly/matlib#17]
In windows it worked well, but in MacOS, when I load matlib package, there is always an error:

Error : .onLoad failed in loadNamespace() for 'rgl', details:
  call: dyn.load(file, DLLpath = DLLpath, ...)
  error: unable to load shared object '/Library/Frameworks/R.framework/Versions/3.3/Resources/library/rgl/libs/rgl.so':
  dlopen(/Library/Frameworks/R.framework/Versions/3.3/Resources/library/rgl/libs/rgl.so, 6): Library not loaded: /opt/X11/lib/libGLU.1.dylib
  Referenced from: /Library/Frameworks/R.framework/Versions/3.3/Resources/library/rgl/libs/rgl.so
  Reason: image not found
Error: package or namespace load failed for ‘matlib’

**Comment by john-d-fox** [comment]
On MacOS, you need to install XQuartz <https://www.xquartz.org/> to use the rgl package, on which matlib depends.

**Comment by wuy3814** [comment]
Thank you very much. I now installed XQuartz and matlib functioned well.
