### ISSUE TITLE
Replace echelon()?

### ISSUE THREAD

**Issue by philchalmers** [friendly/matlib#19]
The current version of `echelon()` just passes the input object to `gaussianElimination()` with the intention of always expressing the left side as an identity matrix. Should this be replaced with what is commonly meant by the echelon form though? E.g., http://stattrek.com/matrix-algebra/echelon-form.aspx

This relates to my point in issue #11 relating to `echelon(..., reduced = FALSE)` to distinguish between reduced/non-reduced form.

**Comment by john-d-fox** [comment]
Hi,

I'm not sure how echelon() got its name, but its misnamed, because it produces the reduced row echelon form. In the precursor to matlib, a never-published package that I wrote to illustrate package writing called matrixDemos, I had a RREF() function.

Best,
 John

**Comment by philchalmers** [comment]
Thanks for the reply, John. Okay, in order to avoid redundancy at some point I'll re-write `echelon()` to have the form 

    echelon <- function(X, reduced = TRUE, ...){
       ret <- if(reduced) gaussianElimination()
       else { some_code() }
       ret
    }

That way the default behaviour stays the same and it's more clear that RREF is being performed, and so that this default can be switched off, if desired.

**Comment by john-d-fox** [comment]
Hi Phil,

> -----Original Message-----
> From: Phil Chalmers [mailto:notifications@github.com]
> Sent: Tuesday, June 27, 2017 11:56 AM
> To: friendly/matlib <matlib@noreply.github.com>
> Cc: Fox, John <jfox@mcmaster.ca>; Comment <comment@noreply.github.com>
> Subject: Re: [friendly/matlib] Replace echelon()? (#19)
> 
> Thanks for the reply, John. Okay, in order to avoid redundancy at some
> point I'll re-write echelon() to have the form
> 
> echelon <- function(X, reduced = TRUE, ...){
>    ret <- if(reduced) gaussianElimination()
>    else { some_code() }
>    ret
> }
> 
> 
> That way the default behaviour stays the same and it's more clear that
> RREF is being performed, and so that this default can be switched off,
> if desired.

Seems reasonable.

Best,
 John

**Comment by friendly** [comment]
I may have introduced the confusion when I imported John's functions, but preferred the name `echelon` to `RREF`, becuause the latter is opaque to students, who should know the concept of echelon form.  

I think in my SAS version I had something like the equivalent of `reduced=T/F`
