### ISSUE TITLE
webgl does not work in linear-equations vignette on CRAN

### ISSUE THREAD

**Issue by jefferis** [friendly/matlib#2]
Dear Michael,

This is nice! Thanks for sharing. 

I noticed that you were using webgl in a vignette (linear-equations) and this is something that I want to do so I took a look. It turns out that the webgl is not working in on CRAN https://cran.r-project.org/web/packages/matlib/vignettes/linear-equations.html. I think that `CanvasMatrix.js` needs to be placed inside `inst/doc` for this to work. Do you know if CRAN will expose this if the file is put there manually?

Best,

Greg Jefferis.

**Comment by friendly** [comment]
thanks for taking a look.

This is my first time building a vignette using `rgl` with the webgl driver.  `CanvasMatrix.js` is of course in `vignettes/`, but AFAIK, package writers are not supposed to put anything in `inst/doc`.
There should be some solution, but I don't know yet what it is.

**Comment by friendly** [comment]
Here is a partial answer from Duncan Murdoch.  I'm not able to depend on the devel version of rgl, so will leave this as is, but perhaps it will sort itself out soonish.

> This stuff has been changing recently.  The idea is that when I'm done CanvasMatrix.js should be embedded in the main .html file, and won't be needed in inst/doc.  From the message, it appears that you're just using the current rgl version on CRAN.  I think it won't include CanvasMatrix.js in your doc directory, so until I get the revisions finished, putting a copy of CanvasMatrix.js into inst/doc is probably necessary.   (I don't know if you're worried about this, but I got a request from a Debian maintainer to also include CanvasMatrix.src.js for licensing reasons.  It includes the copyright notice and license to use as you wish, the CanvasMatrix.js file has that stripped out.)
