### ISSUE TITLE
label of plots in plotEqn()

### ISSUE THREAD

**Issue by charlesjom** [friendly/matlib#22]
![image](https://user-images.githubusercontent.com/12809466/33250454-8f87fd36-d36b-11e7-925d-b935c130ec3f.png)

Is there a way to re-position the label of the plot lines from the plotEqn() function?

**Comment by philchalmers** [comment]
Re-positioning labels is generally not possible with base R plots such as these. The default of `plotEqn()` is to position the label at the first possible x-y pairing for each respective equation plotted, and if these locations are close then overlap will occur (as you are seeing here). 

In this case, you could either try changing the window size of the R plot to try and make the equations overlap less through some trial and error, or pass `plotEqn(..., labels = FALSE)` and include the equations yourself manually. HTH.
