### ISSUE TITLE
QR Function

### ISSUE THREAD

**Issue by dumbdrummer182** [friendly/matlib#23]
The QR function does not seem to be working correctly. It does not return the same value as the base R qr function. Also, the t(q) %*% q doesn't equal I, and q * r doesn't equal A.

**Comment by philchalmers** [comment]
Thanks. Can you provide a simple reproducible example?

**Comment by dumbdrummer182** [comment]
I noticed it while working with the dummy matrix:

X <- matrix(seq(1, 9), nrow = 3, ncol = 3, byrow = TRUE)

**Comment by john-d-fox** [comment]
Here's what I get:
> library(matlib)
> X <- matrix(seq(1, 9), nrow = 3, ncol = 3, byrow = TRUE)
> res <- QR(X)
(. . . some warnings about deprecated computations)
> q <- res$Q
> zapsmall(t(q) %*% q)
     [,1] [,2] [,3]
[1,]    1    0    0
[2,]    0    1    0
[3,]    0    0    0
> q %*% res$R
     [,1] [,2] [,3]
[1,]    1    2    3
[2,]    4    5    6
[3,]    7    8    9

So what's the problem? Your matrix X is of rank 2 -- what did you expect to see?

Best,
 John

-----------------------------
John Fox, Professor Emeritus
McMaster University
Hamilton, Ontario, Canada
Web: socialsciences.mcmaster.ca/jfox/

**Comment by dumbdrummer182** [comment]
Sorry. On the res$R I am getting
       [,1]    [,2]     [,3]
[1,] -8.124 -9.6011 -11.0782
[2,]  0.000 -0.9045  -1.8091
[3,]  0.000  0.0000   0.0000

versus
       [,1]    [,2]     [,3]
[1,] -8.124 -9.6011 -11.0782
[2,]  0.000  0.9045   1.8091
[3,]  0.000  0.0000   0.0000
when using the base R, qr function.

**Comment by john-d-fox** [comment]
Yes, and there's a compensating sign reversal in the Q matrix. As I showed you in my previous response, X is properly recovered.

John
