### ISSUE TITLE
cannot install matlib in Windows 10

### ISSUE THREAD

**Issue by silberc** [friendly/matlib#25]

**Comment by friendly** [comment]
You'll have to be specific -- what was the error? What is your sessionInfo()?

**Comment by silberc** [comment]
I get
there is no package ‘later’

**Comment by philchalmers** [comment]
Can you be more specific than this? What does `sessionInfo()` return after you view this error? Moreover, how can we reproduce this issue on our end? 

We'll close this issue for now, but please feel free to reopen if your issue remains.
