### ISSUE TITLE
problem in ?GramSchmidt

### ISSUE THREAD

**Issue by john-d-fox** [friendly/matlib#27]
Hi,

I noticed that `?GramSchmidt` has this example:
```
# non-invertible matrix; hence, its basis is not orthonormal
(xx <- matrix(c( 1:3, 3:1, 1, 0, -1), 3, 3))
crossprod(xx)
(zz <- GramSchmidt(xx))
zapsmall(crossprod(zz))
```

The statement that the basis isn't orthonormal is wrong and contradicted by the last line of the example. Maybe what was meant is that its dimension is less than the number of columns in `xx`?

John

**Comment by friendly** [comment]
You are right -- good catch, and thx for filing this as an issue.

I don't recall who or why this example was included. Here is replacement text for this example. Does this satisfy?  If so, I'll commit this replacement.

```
# non-invertible matrix; hence, it is of deficinent rank
(xx <- matrix(c( 1:3, 3:1, 1, 0, -1), 3, 3))
R(xx)
crossprod(xx)
# GramSchmidt finds an orthonormal basis
(zz <- GramSchmidt(xx))
zapsmall(crossprod(zz))

```

**Comment by philchalmers** [comment]
Looks like it was me: https://github.com/friendly/matlib/blame/f2f11592b424252497584ca345a7c7cd04a9e853/R/GramSchmidt.R#L29

Not sure why I wrote that. I agree, deficient rank is a better description.

**Comment by john-d-fox** [comment]
Hi Michael,

Sure, that's fine, though "deficinent" is misspelled.

Best,
 John
