### ISSUE TITLE
new branch: devel-0.9.3

### ISSUE THREAD

**Issue by friendly** [friendly/matlib#28]
I thought the fix for #27 was trivial. But I had upgraded to R version 3.6.2 and the latest R Studio. This also upgraded Roxygen, required a newer version of RTools, and left me with 
(a) all .Rd files re-generated, needing to be committed
(b) errors generated on building vignettes

` Error: processing vignette 'gramreg.Rmd' failed with diagnostics:
   pandoc document conversion failed with error 11
   --- failed re-building 'gramreg.Rmd'
`

I'm not  sure how to proceed.  I committed my change to the example in GramSchmidt.R to master. But for everything else, I bumped the pkg version to 0.9.3, ran `devtools::check()`  and created this new branch.

Going forward, I think we should try to fix the problems in the `devel-0.9.3` branch and then merge into master, but I get errors I don't understand from Travis-CI on this branch.

**Comment by philchalmers** [comment]
I can't replicate this on my Windows or Linux box. Perhaps your local error is related to [this issue](https://github.com/rstudio/rstudio/issues/4462)?

**Comment by friendly** [comment]
Done and merged, closes # 28
