### ISSUE TITLE
Building NEWS

### ISSUE THREAD

**Issue by friendly** [friendly/matlib#3]
At present, there is no official NEWS file in the package appearing on CRAN or available via `news("matlib")`.  The devtools / Github way seems to be to just have a file `NEWS.md` in the
top level of the package, but this is not recognized in CRAN builds.

In the `Makefile`, I now have a target "news", so that `make news` does a minimal conversion to
a `NEWS` file.  Is there a better way?

**Comment by philchalmers** [comment]
CRAN supports markdown files for news and readme files (e.g., see rendered version for the .md files for mirt here: https://cran.r-project.org/web/packages/mirt/index.html), so there's no need to have multiple plain-text versions. Just use the `NEWS.md` file directly and remove the ommision line from `.Rbuildignore`.

**Comment by friendly** [comment]
Reminder to self: delete `Makefile` and `NEWS`
