### ISSUE TITLE
sprintf warning

### ISSUE THREAD

**Issue by friendly** [friendly/matlib#36]
Msg from Brian Ripley:

R-devel has a new runtime check in sprintf() that all arguments are used by the format and this is showing one or more warnings in the checks of these packages, usually in the examples.  E.g.

Warning in sprintf("%s$", extension, ignore.case = TRUE) :
   argument not used by format
Warning in sprintf("<a href='%s'>%s</a>", getFunctionLinks(tokens[w]), tokens[w],  :
   argument not used by format

Please investigate (by running  R CMD check with the latest R-devel and grepping the .Rcheck directory).  In some cases the warning seems to be from another package, usually one with the same maintainer.  If from one not on this list, please let CRAN and its maintainer know.  If you think this is a false positive, please contact Tomas Kalibera (in Cc:).

**Comment by friendly** [comment]
I checked the source: `sprintf()` is found in

- Gramschmidt.R
- LU.R
- showEqn.R


I cannot see anywhere that there are "unused arguments"

**Comment by friendly** [comment]
Ah:  The message says "usually in the examples".  For LU we have

    #'   LU(A, b, verbose=TRUE)
    #'   LU(A, b, verbose=TRUE, fractions=TRUE)

and `...` may be getting passed to `sprintf` somewhere.

**Comment by philchalmers** [comment]
I can't reproduce the issue on my r-devel `(2020-10-23 r79366)`, and from what I can tell this seems likely to be a false positive. In all in-line instances of `sprintf()` the input arguments appear valid, and there are no direct instances of `...` being passed to this function. Perhaps CRAN's sensitivity tests are confused by instances where functions are passed within `sprintf()` calls, [such as this one](https://github.com/friendly/matlib/blob/a0d87792c0d406dda530b23c2a20fe67019ad32d/R/LU.R#L140) in `LU.R`?

**Comment by friendly** [comment]
It could be that this new check gets confused. I don't have r-devel. The one example I though might be troublesome was the one
    LU(A, b, verbose=TRUE, fractions=TRUE)

Could you follow up checking this and/or with an email to Tomas Kalibera <tomas.kalibera@gmail.com> ?

**Comment by philchalmers** [comment]
Found and patched the issue. Turns out it was a length mismatch between the sprintf expression and the number of R objects passed to `sprintf()` (doesn't show up on any checks, so `grep` really was required in the `matplot-Ex.Rout` file).
