### ISSUE TITLE
showEqn (simplify=TRUE) error

### ISSUE THREAD

**Issue by rjrovetti** [friendly/matlib#45]
Coefficient is incorrect in some cases when simplify=TRUE

Reproducible case:
M = matrix(c(-10,2,3,4), ncol=2)
b = c(1,2)
showEqn(M,b)
showEqn(M,b, simplify=TRUE)

**Comment by friendly** [comment]
John Fox contributed a fix to this, presently on a testing branch

**Comment by philchalmers** [comment]
Looks good now.

``` r
library(matlib)
M = matrix(c(-10,2,3,4), ncol=2)
b = c(1,2)
showEqn(M,b)
#> -10*x1 + 3*x2  =  1 
#>   2*x1 + 4*x2  =  2
showEqn(M,b, simplify=TRUE)
#> -10*x1 + 3*x2  =  1 
#>   2*x1 + 4*x2  =  2
```

<sup>Created on 2022-12-06 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
