### ISSUE TITLE
`vectors` gives unexplained warnings & `pos.lab` doesn't work

### ISSUE THREAD

**Issue by friendly** [friendly/matlib#50]
In the script below, I'm trying to illustrate the idea of projections of a matrix X using two projection matrices, P1 and P2

```
vals <- c(0, 10)
X <- expand.grid(x1 = vals, x2=vals, x3=vals) |> as.matrix()

# project on just x1, x2 plane
P1 <- rbind(diag(2), c(0,0))
Y1 <- X %*% P1

# oblique projection
P2 <- matrix(c(0.71, 0.71, 0, -0.42, .42, 0.84), ncol=2)
Y2 <- X %*% P2
```

Part of the illustration is to show the vectors x1, x2, and x3 in (y1, y2) space, e.g.:

![fig-proj-vectors-1](https://github.com/friendly/matlib/assets/456353/d4edf07e-dc5e-4947-b6ba-68b7e3f7e49a)

Code:
```
# draw X vectors in Y space
xlim <- ylim <- c(-1.1, 1.1)
axes.x <- c(-1, 1, NA, 0, 0)
axes.y <- c(0, 0, NA, -1, 1)
labs <- c(expression(x[1]), expression(x[2]), expression(x[3]))

op <- par(mar=c(4, 5, 1, 1)+.1)
plot(xlim, ylim, type = "n", asp=1,
     xlab = expression(y[1]), ylab = expression(y[2]),
     cex.lab = 1.8)
plotrix::draw.circle(0, 0, 1, 
                     col = adjustcolor("skyblue", alpha = 0.2))
lines(axes.x, axes.y, col = "grey")
matlib::vectors(P1, labels = labs, cex.lab = 1.8, lwd = 3)
```

When I run this I get warnings I don't understand or know how to avoid:

```
1: In arrows(..., angle = ang) :
  zero-length arrow is of indeterminate angle and so skipped
2: In arrows(..., angle = ang) :
  zero-length arrow is of indeterminate angle and so skipped
3: In arrows(..., angle = ang) :
  zero-length arrow is of indeterminate angle and so skipped
4: In arrows(..., angle = ang) :
  zero-length arrow is of indeterminate angle and so skipped
...
```

As well, I'd like to alter the position of the labels.  But, with the following call, no labels are produced:

```
matlib::vectors(P1, labels = labs, cex.lab = 1.8, lwd = 3, pos.lab = c(4, 3, 0))
```

**Comment by philchalmers** [comment]
Hi Michael,

Your object `P1` has the third row set to [0,0], which means that the `arrows()` function is trying to draw an arrow to and from itself. If you remove this one from the script (`P1 <- P1[-3,]`) then the warnings will disappear, though the origin location will not be included, of course. 

Regarding the second point, I believe the output will be drawn if after `P1` is reduced to two rows then 

```r
matlib::vectors(P1, labels = labs[-3], cex.lab = 1.8, lwd = 3, pos.lab = c(4, 3))
```
should draw the supplied labels. HTH.

**Comment by friendly** [comment]
Ah, of course. Silly me.  
But that situation should be handled internally, I think

**Comment by john-d-fox** [comment]
Hi Michael,

On 2024-02-09 9:45 p.m., Michael Friendly wrote:
> 	
> Caution: External email.
> 
> 
> Ah, of course. Silly me.
> But that situation should be handled internally, I think


I'm glad that the mystery was solved -- before I read your original message.

I'm not sure what resolving the situation internally would entail. 
Shouldn't a zero-length vector produce a warning, which is what appears 
to happen currently?

Best,
  John

**Comment by friendly** [comment]
What was perplexing was that it gave 7 warning msgs for the case where the last row of `P` was zeros.
I modified the code in vectors to check for near zero length & omit them, with one warning

**Comment by friendly** [comment]
Closed as completed
