### ISSUE TITLE
renaming symbolicMatrix to latexMatrix

### ISSUE THREAD

**Issue by john-d-fox** [friendly/matlib#55]
I've moved the contents of `dev/Arith.R` into `R/symbolicMatrix.R`. In the process, I improved some of the operator and function methods (e.g., unary `-` is now supported). Then I uniformly renamed `symbolicMatrix` to `latexMatrix` in `R/*.R` and a few other places, but *not* in the vignettes nor in the contents of `doc/*.*.` 

In checking the package, I encountered the following warning:
`Warning: 'rgl.init' failed, running with 'rgl.useNULL = TRUE'`

John

**Comment by john-d-fox** [comment]
I fixed the latex-equations vignette to reflect the change from `symbolicMatrix()` to `latexMatrix()`. The package now checks --as-cran without errors or notes.

I started correcting the content of this vignette (beyond the change in the name of function) but then noticed that I wasn't listed as an author, so I stopped.

**Comment by philchalmers** [comment]
I see the same warning on my checks as well, though only on my headless server (locally the warning doesn't get raised,so it's likely innocuous). I do however get the following on my R/dev check:

```
* checking CRAN incoming feasibility ... [5s/14s] NOTE
Maintainer: ‘Michael Friendly <friendly@yorku.ca>’

Found the following (possibly) invalid URLs:
  URL: http://stackoverflow.com/questions/39730889/rgl-drawing-a-cube-with-colored-faces-vertex-points-and-lines (moved to https://stackoverflow.com/questions/39730889/rgl-drawing-a-cube-with-colored-faces-vertex-points-and-lines)
    From: inst/doc/inv-3d.html
    Status: 200
    Message: OK
```


Regarding the files in 'dev/', I have no objections to any of the vignettes being modified.

**Comment by john-d-fox** [comment]
Hi Phil,

On 2024-08-15 12:34 p.m., Phil Chalmers wrote:
> 	
> Caution: External email.
> 
> 
> I see the same warning on my checks as well, though only on my headless 
> server (locally the warning doesn't get raised,so it's likely 
> innocuous). I do however get the following on my R/dev check:
> 
> |* checking CRAN incoming feasibility ... [5s/14s] NOTE Maintainer: 
> ‘Michael Friendly ***@***.***>’ Found the following (possibly) 
> invalid URLs: URL: http://stackoverflow.com/questions/39730889/rgl- 
> drawing-a-cube-with-colored-faces-vertex-points-and-lines (moved to 
> https://stackoverflow.com/questions/39730889/rgl-drawing-a-cube-with- 
> colored-faces-vertex-points-and-lines) From: inst/doc/inv-3d.html 
> Status: 200 Message: OK |
> 
> Regarding the files in 'dev/', I have no objections to any of the 
> vignettes being modified.

I'll leave it to the authors of the vignette to bring it up-to-date. In 
its current state it omits most of the capabilities associated with 
latexMatrix() and methods for the objects it produces.

Best,
  John

**Comment by friendly** [comment]
@john-d-fox You should certainly be an author, now that latexMatrix has been so far extended. It was only that Phil got the first draft started & I fleshed it out, as symbolicMatrix was at the time.

**Comment by john-d-fox** [comment]
On 2024-08-15 4:59 p.m., Michael Friendly wrote:
> 	
> Caution: External email.
> 
> 
> @john-d-fox <https://github.com/john-d-fox> You should certainly be an 
> author, now that latexMatrix has been so far extended. It was only that 
> Phil got the first draft started & I fleshed it out, as symbolicMatrix 
> was at the time.

OK, I'll extend the vignette with the new material on latexMatrix(), 
etc., sometime during the next few days.

It didn't seem appropriate for me simply to edit your and Phil's 
vignette -- I made small changes to it so that the package would check 
before realizing that my name wasn't on it -- nor to add my name as an 
author uninvited.

John

**Comment by friendly** [comment]
Would be great if you wrote a section on matrix arithmetic. I'll look it over and see what's needed/useful in the rest.

**Comment by john-d-fox** [comment]
Hi,

On 2024-08-16 4:56 a.m., Michael Friendly wrote:
> 	
> Caution: External email.
> 
> 
> Would be great if you wrote a section on matrix arithmetic. 

That's essentially what I plan to do.

John

**Comment by john-d-fox** [comment]
On 2024-08-16 4:56 a.m., Michael Friendly wrote:
> 	
> Caution: External email.
> 
> 
> Would be great if you wrote a section on matrix arithmetic. 

I've now added a draft section on computing with "matrixLatex" objects. 
I think that it covers all of the bases, but I may have missed something.

John

**Comment by friendly** [comment]
Just tried to render it -- I get

```
processing file: latex-equations.Rmd
                                                                                                                          
Error in `as.double.latexMatrix()`:
! matrix cannot be coerced to 'double' ('numeric')
Backtrace:
 1. base::as.numeric(...)
 2. matlib:::as.double.latexMatrix(...)

Quitting from lines 221-223 [coerce-to-numeric-with-locals] (latex-equations.Rmd)
Execution halted
```

I suspect it may be something w/ my laptop.  Let me know if it builds for you.

**Comment by philchalmers** [comment]
Looks to compile okay on my end. Removed the `cat()` call again in example as these are no longer needed; hopefully this doesn't result in a conflict...

**Comment by philchalmers** [comment]
Oh I see, it appears we have two very similar files that should be merged (see https://github.com/friendly/matlib/blob/master/dev/Eqn_test.Rmd). Before proceeding it may be time to clean up some files in `dev/`, perhaps moving some to `dev/archive/` if we're not willing to dispose of some just yet.

**Comment by john-d-fox** [comment]
Hi,

On 2024-08-16 2:59 p.m., Michael Friendly wrote:
> 	
> Caution: External email.
> 
> 
> Just tried to render it -- I get
> 
> |processing file: latex-equations.Rmd Error in 
> `as.double.latexMatrix()`: ! matrix cannot be coerced to 
> 'double' ('numeric') Backtrace: 1. base::as.numeric(...) 2. 
> matlib:::as.double.latexMatrix(...) Quitting from lines 221-223 [coerce- 
> to-numeric-with-locals] (latex-equations.Rmd) Execution halted |
> 
> I suspect it may be something w/ my laptop. Let me know if it builds for 
> you.

I checked that everything worked prior to committing my changes, 
including running R CMD check --as-cran.

My guess: You need to reinstall matlib to bring it up-to-date.

John

**Comment by friendly** [comment]
Yes -- I usually do `devtools::load_all()`, but in this case install was required.

Is it OK if I do some minor edits on the vignette?

**Comment by john-d-fox** [comment]
On 2024-08-16 3:40 p.m., Michael Friendly wrote:
> 	
> Caution: External email.
> 
> 
> Yes -- I usually do |devtools::load_all()|, but in this case install was 
> required.
> 
> Is it OK if I do some minor edits on the vignette?

Yes. I'm finished with it for now pending comments on the new section.

John
