### ISSUE TITLE
Eqn() doesn't set eqn. numbers correctly

### ISSUE THREAD

**Issue by john-d-fox** [friendly/matlib#56]
I think that this was raised previously, but AFAICS, it's not been fixed. `Eqn()` doesn't appear to set equation numbers correctly nor to handle equation labels properly. See the SVD example in the [`latex-equations` vignette](https://friendly.github.io/matlib/articles/latex-equations.html) for an illustration of the problem.

**Comment by friendly** [comment]
@philchalmers wrote a `dev/test-eqn-vignette.Rmd` that does work, using the same YML header. I haven't found why it doesnt in the vignette

**Comment by philchalmers** [comment]
This is related to the knitr-pandoc workflow, which makes compilation of HTML documents less universal. I'd have to look into what build chain `pkgdown` uses to see if it can be compiled differently (though I'm quite skeptical .....). We discussed this briefly in issue #52, which is fixed for isolated HTML documents with controlled build flags.

**Comment by philchalmers** [comment]
I see the issue now, and it's not with `Eqn()`. For some bizarre reason the math labels for mathjax must be of the form `eq:...`, not `eqn:...`. See here in the attention box: https://bookdown.org/yihui/bookdown/markdown-extensions-by-bookdown.html

**Comment by john-d-fox** [comment]
Actually, if I'm reading the correct part of the document, what it says 
is that labels are of the form \#eq:label .  Maybe Eqn() attaches the 
\#. Since you have much more experience with Bookdown than I do, I'll 
let you or Michael try to fix this in the vignette.

Thanks for tracking this down.

**Comment by philchalmers** [comment]
Hi John,

`Eqn()` now checks whether the first two characters of the labels equal `eq` for HTML documents, so this quirk is now easier to track and fix.

Similarly, switching between `\ref{eq:lab}` and `(#eq:lab)` for in-line referencing felt tedious and too document specific, so I added an inline function `ref()` to do a similar switching of output behaviour depending on the detected output type.  So now rather than using the LaTeX or HTML document specific forms we can just use ` ```r ref('eq:lab')``` `.

**Comment by friendly** [comment]
Thx @philchalmers for tracking this down.
Given that equation numbers are not always used, perhaps the default should be `number=FALSE` in Eqn()?

**Comment by friendly** [comment]
In the `latex-equations` vignette, now get an eqn # for the first SVD example, but not in the 2nd.
`ref("eq:svd")` still not working.

**Comment by philchalmers** [comment]
Hi Michael,

I agree about `number = FALSE` as the default. Also, I added the inline version of references to fix the problems in the vignette (it's ` r ref("eq:lab") `, I mistyped earlier).

**Comment by friendly** [comment]
In the vignette for the SVD example, now adding `number=TRUE` doesn't produce an equation number.

```
Eqn(latexMatrix("u", "n", "k", lhs = ''),
    latexMatrix("\\lambda", "k", "k", diag=TRUE),
    latexMatrix("v", "k", "p", transpose = TRUE), number = TRUE)
```

**Comment by philchalmers** [comment]
Another special HTML case, I'm afraid. For numbering equations \begin{equation} is not enough for MathJax, you need to specify a label. I've added another `stop()` to make this more obvious.

**Comment by philchalmers** [comment]
I've removed the `number` argument to make the behaviour more consistent. To include an equation number for LaTeX and HTML users now need to specify a suitable `label`, in which case the resulting equation will be numbered (leaving label as NULL will not number the equation, which is the default). Though not required for LaTeX I do see this as good practice.

**Comment by friendly** [comment]
Wonderful! It did seem confusing to have both `number` and `label`.
The vignette now works.
