### ISSUE TITLE
Functions to add decorators over or under matrices {over,under}{set,brace}

### ISSUE THREAD

**Issue by friendly** [friendly/matlib#70]
As I'm using `latexMatrix()` and `Eqn()` more and more, another thing I'd like to be able to do is add labels under or over a matrix in an equation to identify terms and add braces under or over to identify parts of an expression. Can anyone help?

To show what I want to achieve, here is an example of overset labels, which I rendered by manually tweaking LaTeX code:

![SSP-decomp](https://github.com/user-attachments/assets/acf1557c-4b18-404b-99a8-6b917e038d53)

Here is one for underbracing and labeling a subexpression in a formula, here for the Hat matrix in regression:

![hat-matrix-underbrace](https://github.com/user-attachments/assets/1f7f3b5d-b37a-4ee4-9fa5-26c7234dd077)

I defined some simple functions, `underset()`, `overset()`, `underbrace()`, and `overbrace()` for these purposes in `dev/under-over.R` See the tests I defined there.

My working example for the first case is:

```
  data(dogfood, package = "heplots")
  dogfood.mod <- lm(cbind(start, amount) ~ formula, data=dogfood) 
  dogfood.aov <- car::Anova(dogfood.mod) 
  SSP_H <- dogfood.aov$SSP[["formula"]]   |> round(digits = 2)
  SSP_E <- dogfood.aov$SSPE               |> round(digits = 2)
  SSP_T <- SSP_H + SSP_E
```

I can `overset()` one of these terms by doing this explicitly in the call to `Eqn()`, but not when I use `Eqn(overset())` to do that work.

```
  # do overbrace directly: WORKS
  Eqn("\\overset{\\mathbf{SSP}_T}{", SSP_T, "}")
  
  # but these don't work:
  Eqn(overset(SSP_H, "\\mathbf{SSP_H}"))
  Eqn(overset(SSP_E, "\\mathbf{SSP_E}"))
```
For the H matrix, what I get is:

![image](https://github.com/user-attachments/assets/d4dcfc75-283a-4c3e-9461-d18fb774bf6e)

I also tried the following, but the result is worse still:

```
  H <- latexMatrix(SSP_H)
  Eqn(overset(H, "\\mathbf{SSP_H}"))
```

Under/over bracing works, at least with straight LaTeX expressions. Not tested for `latexMatix()`, but this is probably the same problem I encountered above.

```
  # I want to generate the equation \hat{y} = X (X'X)^{-1} X' y with a brace underneath showing the H matrix
  # This manual LaTeX works:
  eqn <- "
  \mathbf{\hat{y}} 
   = \underbrace{\mathbf{X}(\mathbf{X}^{\top}\mathbf{X})^{-1}\mathbf{X}^{\top}}_\mathbf{H}\mathbf{y}   
  "
  
  # generate this with underbrace()
  H <- "\\mathbf{X}(\\mathbf{X}^{\\top}\\mathbf{X})^{-1}\\mathbf{X}^{\\top}"
  underbrace(H, "\\mathbf{H}")
  
  # Do this with Eqn() - WORKS, at least when all the elements are just symbols, not matrices
  Eqn("\\mathbf{\\hat{y}} =", underbrace(H, "\\mathbf{H}"), "\\mathbf{y}")

  # We can even combine this with overbrace 
  Eqn(overbrace(underbrace(H, "\\mathbf{H}"), "\\mathbf{\\hat{y}}"))
```

**Comment by friendly** [comment]
Looking at my examples again, I think the problem is that I should be using John's extractor functions like `getBody()` etc. inside my `overset()` etc., but I can't see what form this should take.

**Comment by john-d-fox** [comment]
I'm probably the wrong person to address this problem because my guess is that it pertains to `Eqn()` (I could be wrong). In fact, I don't quite see how `overset()` and `underset()` are supposed to work. They would have get the LaTeX corresponding to their first argument.

A couple of additional points:

(1) The difference is probably trivial and not the source of the problem, but `\\mathbf{SSP}_T` isn't quite similar to `\\mathbf{SSP_H}` in that the subscript in the latter in bolded.

(2) In any event, `overset(SSP_H, "\\mathbf{SSP}_H")` doesn't seem a whole lot simpler to me than `"\\overset{\\mathbf{SSP}_H}{", SSP_H, "}"`.  Is it really necessary (or even desirable) to introduce functions like `overset()` and `underset()`? `latexMatrix()`, the various methods associated with it, and `Eqn()` are already quite complicated. I don't think that we'll ever be able to make the LaTeX functions in **matlib** as general as LaTeX itself.

**Comment by friendly** [comment]
Thanks for the reply.
I'm not sure whether a solution to the problem with `overset()` is rooted in `latexMatrix()` or `Eqn()`.

But on your point (2), when  use `\\overset{}` directly for a single matrix, it works:

```
  Eqn("\\overset{\\mathbf{SSP}_T}{", SSP_T, "}")
```
![image](https://github.com/user-attachments/assets/2c805c7d-4486-455a-9fee-e6c8339da873)

But I get an error (argument is missing, with no default) I can't track down trying to do my main example in this way:

```
>   Eqn("\\overset{\\mathbf{SSP}_T}{", SSP_T, "}", 
+       "+",
+       "\\overset{\\mathbf{SSP}_H}{", SSP_H, "}",
+       "=",
+       "\\overset{\\mathbf{SSP}_E}{", SSP_E, "}",
+   )
Error in Eqn("\\overset{\\mathbf{SSP}_T}{", SSP_T, "}", "+", "\\overset{\\mathbf{SSP}_H}{",  : 
  argument is missing, with no default
Warning message:
In file.remove(tmpfile) :
  cannot remove file 'C:\Users\friendly\AppData\Local\Temp\RtmpmQqPww\file3d102ef54c64', reason 'Permission denied'
```

Perhaps @philchalmers can see what is wrong here.

**Comment by friendly** [comment]
I also tried feeding a `latexMatrix()` to `overset()`, and get this very weird result

```
Eqn(overset(latexMatrix(SSP_H), "\\mathbf{SSP_H}"))
```

![image](https://github.com/user-attachments/assets/61cf4bc7-ec0d-42d6-a014-6a37b9108e6c)

So,  my attempt at `overset()` is probably naive, but it would be nice to be able to do this some way.

**Comment by philchalmers** [comment]
Hi Michael,

`overset()` isn't behaving correctly because you're pasting strings together with matricies, which are often applied to each element of the matrix or require the matrix to be collapsed.

```r
overset <- function(x, over){
  paste0("\\overset{", over, "} {", x, "}" )
}

Eqn(overset(SSP_H, "\\mathbf{SSP_H}"))

\begin{equation*}
\overset{ \mathbf{SSP_H} } { 9.69 -70.94 -70.94 585.69 }\end{equation*}
```

For this to work correctly you'd need to follow a similar logic to the other `latexMatrix()` constructor add-ons where the information is added directly to the object itself so that `print()` renders correctly.

**Comment by philchalmers** [comment]
Are you aiming for something like this?

```r
overset <- function(x, over){
  return(c("\\overset{", over, "} {", getLatex(x), "}" ))
}

Eqn("\\overset{\\mathbf{SSP}_T}{", latexMatrix(SSP_T), "}")
```

If so some type checking would be required for `x`.

**Comment by friendly** [comment]
Thanks, Phil

Is this what you mean, or is something more elaborate required?
```
overset <- function(x, over){
  if(is.matrix(x)) x <- latexMatrix(x)
  over <- paste0("\\overset{", over, "}")
  return(c(over, "\n{", getLatex(x), "}\n" ))
}
```

My example, the way I'd like to be able to do it now works:

```
  Eqn(overset(SSP_T, "\\mathbf{SSP}_T"), "=",
      overset(SSP_H, "\\mathbf{SSP}_H"), "+",
      overset(SSP_E, "\\mathbf{SSP}_E")
      )
```
Renders as:

![image](https://github.com/user-attachments/assets/c4ba62c5-7269-4ede-94d3-de5eb89ab355)

It requires that the `display.labels` option be set `FALSE`

```
options(print.latexMatrix = list(display.labels=FALSE))
```

**Comment by friendly** [comment]
Here's a revised function, with additional features:

* label defaults to the name of the matrix
* allow different styles for setting the label

Any suggestions?
```
overset <- function(x, 
                    label,
                    label.style = c("mathbf", "mathrm", "mathit", "mathsf", "mathcal", "mathtt", " ")
                    )
  {
  if (missing(label) && is.matrix(x)) label <- deparse(substitute(x))
  if (is.matrix(x)) x <- latexMatrix(x)
  label.style <- match.arg(label.style)
  if (label.style != " ") label <- paste0("\\", label.style, "{", label, "}")
  over <- paste0("\\overset{", label, "}")
  return(c(over, "\n{", getLatex(x), "}\n" ))
  }
```

Some tests that work:

```
  A <- matrix(1:4, 2, 2)
  B <- matrix(4:1, 2, 2)
  AB <- A + B
  Eqn(overset(A, "A"))
  # test missing label
  Eqn(overset(A))
  
  # test label styles
  Eqn(overset(A, "A", label.style = "mathtt"))
  Eqn(overset(A, "AAAAA", label.style = "mathcal"))
  Eqn(overset(A, "A", label.style = " "))
  Eqn(overset(A, "\\Large{A}", label.style = " "))

  # test equations
  Eqn(overset(A, "A"), "+",
      overset(B, "B"), "=",
      underset(AB, "A+B"))
```

**Comment by philchalmers** [comment]
This looks reasonable to me. My only concern is that `\overset{}` isn't only for matrices (e.g., `Eqn('a', overset('?', '='), 'b')` should be valid), and stylistically I'd recommend using the `Eqn_` prefix so that the TeX modifiers all have the same structure. 

We certainly could start using the native TeX command convention, though I worry that these will be more difficult to locate for less TeX fluent users. Part of me also wonders if `Eqn()` and friends should be isolated in it's own package where `matlib` adds the functions as a dependency..... One problem at a time though!

**Comment by friendly** [comment]
So, there seem to be three cases to consider for the arg `x`:

* a character string, assumed to be a LaTeX expression, passed to `\overset{x}` as is
* a matrix -> converted, via `latexMatrix(x) |> getLatex()`
* a `"latexMatrix"` object extracted via `getLatex(x)`

I think that the following function does the above. I'm agreeable using `Eqn_overset()` for consistency with your naming scheme (but I'd also favor shorthand aliases, like `overset <- Eqn_overset` for conciseness).

```
overset <- function(x, 
                    label,
                    label.style = c("mathbf", "mathrm", "mathit", "mathsf", "mathcal", "mathtt", " ")
                    )
 {
  if (missing(label) && is.matrix(x)) label <- deparse(substitute(x))
  if (is.matrix(x)) x <- latexMatrix(x)  |> getLatex(x)
  label.style <- match.arg(label.style)
  if (label.style != " ") label <- paste0("\\", label.style, "{", label, "}")
  over <- paste0("\\overset{", label, "}")
  return(c(over, "\n{", x, "}\n" ))
  }
```

But, I re-read your docs for `?Eqn` and my function doesn't seem to handle the full features of a `"latexMatrix"` object.

A test for `if (inherits (x, "latexMatrix"))` might solve this, but at the moment I can't see how to do that and allow the
other possibilities for `x`.

A couple of quick tests with the current version:

```
  # test latexMatrix objects
  Lambda <- latexMatrix("\\lambda", nrow=2, ncol=2,
                   diag=TRUE)
  # OK -- but note the docs use "\lambda" here
  Eqn(Lambda)
  # fails miserably
  Eqn(overset(Lambda, "\\Lambda"))
```

I've just pushed my latest version to `dev/under-over.R`

**Comment by john-d-fox** [comment]
Reading the last few comments made it clear to me how much I forgot (or repressed) about how `latexMatrix()` and `Eqn()` work, including the stuff that I implemented.

If `overset()` is to work with objects of different classes, why not make it generic, with methods for the various classes, so that, e.g., `getLatex()` can be invoked automatically for a `"latexMatrix"` object? As in (not tested)
```
overset.latexMatrix <- function(x, label, ...){
  overset(getLatex(x), label, ...) # invoking the default method
}
```

**Comment by philchalmers** [comment]
@friendly your examples look okay to me ...

![image](https://github.com/user-attachments/assets/266e8d0b-1ba6-4087-bb51-a90294ee71e5)

I know what you mean about `outset()` vs `Eqn_outset()`. If this alias were to be used in the package I'd recommend we do this for all the `Eqn_*` definitions, of which there are currently 5 others (newline, hspace, etc). 

@john-d-fox I'm generally for using S3 methods too, though with only ~3 class use cases this feels like a matter of preference. I'm fine either way.

**Comment by philchalmers** [comment]
I was able to replicate your issue, Michael, and patched the new dev functions accordingly. Each function will also now work with a character (or rather, atomic) vector input (e.g., `Eqn(overbrace('a + b + c'))`).

**Comment by friendly** [comment]
@john-d-fox I see what you mean by making `overset()` generic, but I think that this is overkill for what is now handled internally for the possible simple type of `x`. More complicated examples might prove me wrong. :)

I've renamed the file to `dev/over_under.R` and fleshed out roxygen doumentation, which should all wind up in `over_under.Rd`

I also added aliases, `Eqn_overset()` etc. for each of these. I agree with Phil that his `Eqn_newline()` etc. should have simple aliases like just `\newline()`

I think this is now sufficiently mature to copy to `R/`, where I can test the documentation.

**Comment by friendly** [comment]
I copied the function to `R/` and ran `document()`. I get this error and can't see what's causing it.

```
> devtools::document()
ℹ Updating matlib documentation
ℹ Loading matlib
✖ In topic 'over_under.Rd': Skipping; no name and/or title.
```

Only a file `man/overset.Rd` is generated.  The head of my `over_under.R` seems to contain the necessary info:

```
#' @name over_under
#' @aliases overset underset overbrace underbrace 
#' @aliases Eqn_overset Eqn_underset Eqn_overbrace Eqn_underbrace 
#' @title 
#' Functions to Add Labels and/or Braces 
#' 
#' @description
```

Can anyone see what is wrong?

**Comment by philchalmers** [comment]
There's no function called `over_under`, so the initial .Rd file doesn't get generated. Why not just put them in `#' @rdname Eqn` (replace all), and add the same location for the first function overset? That way everything is in the same place.

**Comment by friendly** [comment]
Fixed now in `over_under.R`. 

If you want me to change this to `#' @rdname Eqn`, I can, but it seems like it would be clearer to have a different doc for `Eqn_helpers` including these and your `Eqn_newline()` etc. in one place, separate from `Eqn`.

The way it is, all the arguments for the helpers are merged with those for `Eqn()` itself, which I think is confusing.

**Comment by philchalmers** [comment]
Agreed, though circling back to my earlier comment, would it make sense to extract the `Eqn()` functions and put them into an isolated package? That would satisfy my search desideratum as one can use `Eqn::newline()` or `newline()` directly when attached, and would make documentation substantially less clunky. There would of course be strong dependency between `matlib` and this package, but I don't see this as an issue per se.

**Comment by friendly** [comment]
I documented the fns in over_under.R as `Eqn_helpers`. Works fine.

Should I go ahead and change the `Eqn_newline()` and similar in `Eqn.R`, or would you? I'm a bit reluctant to mess with your code for fear of doing something you don't like.

If I did it, I would move all those functions into a new file, `Eqn_helpers.R` and make the documentation coherent.

At some point we might want to move all of this LaTeX stuff to a new package, but that's a bigger task than I want to contemplate now.

**Comment by philchalmers** [comment]
> Should I go ahead and change the `Eqn_newline()` and similar in `Eqn.R`, or would you? I'm a bit reluctant to mess with your code for fear of doing something you don't like.

Feel free to do the same (you're using these equations much more than I), though note that `Eqn_text()` will need a different short name to avoid conflict with `text()`. The rest should be fine as short forms.

> If I did it, I would move all those functions into a new file, `Eqn_helpers.R` and make the documentation coherent.

Agreed. This will also help clean up the `Eqn()` documentation which is currently too busy.

> 
> At some point we might want to move all of this LaTeX stuff to a new package, but that's a bigger task than I want to contemplate now.

Works for me. 

As an aside, I've been playing around with raw strings to avoid the "leaning toothpick syndrome" so that 

```r
"\\Lambda=\\frac{\\alpha}{\\beta}}"
```

could be written in common LaTeX speak as 

```r
r"{\Lambda=\frac{\alpha}{\beta}}}"
```
though sadly I don't see a way to functionalize this yet ...  I think we should include a few examples showing how to copy-paste straight LaTeX code into `Eqn()` and friends as there's likely instances where this would be useful (and in my experience, few R users are even aware of raw strings). Not an issue to be addressed here, of course, just planting an attention seed for later.

**Comment by friendly** [comment]
OK, did that. The docs for `Eqn()` & `Eqn_helpers()` look good to me, but take a look before I close this issue.

I don't quite understand raw strings, at least in this context. These don't work:

```
> Eqn(r"\mathbf{X} = \mathbf{U} \mathbf{\Lambda} \mathbf{V}", label='eq:svd')
Error: malformed raw string literal (<input>:1:7)
> Eqn(r("\mathbf{X} = \mathbf{U} \mathbf{\Lambda} \mathbf{V})", label='eq:svd')
Error: '\m' is an unrecognized escape in character string (<input>:1:9)
```

**Comment by philchalmers** [comment]
The raw character input needs a form like `r"(...)"` or my preferred `r"{...}"`, so this works:

```r
Eqn(r"{\mathbf{X} = \mathbf{U} \mathbf{\Lambda} \mathbf{V}}", label = 'eq:svn')
```

**Comment by philchalmers** [comment]
Docs look good to me save some extra spaces in the examples; thanks for checking! Feel free to close.

**Comment by friendly** [comment]
Over, under & OUT
