### ISSUE TITLE
printing matrices and vectors side-by-side

### ISSUE THREAD

**Issue by friendly** [friendly/matlib#8]
In this query to stackoverflow, http://stackoverflow.com/questions/39419622/printing-matrices-and-vectors-side-by-side, I ask about code to print a collection of matrices, vectors, and character strings side-by-side, to illustrate matrix equations and expressions.  My main example of what I want to do is this expression from SAS/IML

```
print A ' * ' x '=' (A * x) '=' b;

                A                     X   #TEM1001       B
                1     1    -4  *  0.733 =        2 =     2
                1    -2     1     -0.33          1       1
                1     1     1      -0.4          0       0
```

There was one answer so far, but not as general as I'd like.  Is it posible to do better?

**Comment by philchalmers** [comment]
What's not so general about it? I'm not seeing what's missing. 

Also, IMHO the input form looks terrible (SAS included). I think it would be more natural to accept something like 

``` r
print_mat('A %*% x = (A %*% x) = b')`
# or
print_mat('A * x = (A * x) = b')`
```

where anything in the `()` parentheses becomes evaluated based on the defined objects in the working envir.

**Comment by philchalmers** [comment]
Hi Michael,

How's something like this? It's a little less convoluted than the SO approach. 

```r
print_mat <- function(..., space = 1) {
    
    # get arguments
    args <- list(...)
    chars <- sapply(args, is.character)
    args[chars] <- lapply(args[chars], function(x) 
        paste0(rep(' ', space), x, rep(' ', space)))
    
    # vectors to matrix
    pick <- sapply(args, function(x) !is.matrix(x))
    args[pick] <- lapply(args[pick], as.matrix)
    
    nrows <- sapply(args, nrow)
    ncols <- sapply(args, ncol)
    
    mat <- matrix('', max(nrows), sum(ncols))
    nms <- rep('', sum(ncols))
    nms[cumsum(ncols)] <- names(args)
    
    for(i in 1L:max(nrows))
        mat[i, ] <- do.call(c, lapply(args, function(x) 
            if(nrow(x) >= i) as.character(x[i, ]) else rep('', ncol(x))))
    
    ret <- data.frame(mat, stringsAsFactors = FALSE)
    colnames(ret) <- nms
    print(ret, row.names=FALSE)
}


A <- matrix(c(2, 1, -1,
              -3, -1, 2,
              -2,  1, 2), 3, 3, byrow=TRUE)
x <- c(2, 3, -1)

print_mat(A = A, "*", x = x, '=', b = A %*% x)

        A      x       b
  2  1 -1  *   2  =    8
 -3 -1  2      3     -11
 -2  1  2     -1      -3

A = matrix(c(0.5, 1, 3, 0.75, 2.8, 4), nrow = 2)
x = c(0.5, 3.7, 2.3)
y = c(0.7, -1.2)
b = A %*% x - y
print_mat(A = A, " * ", x = x, " - ", y = y, " = ", b = b)

            A         x          y            b
 0.5    3 2.8   *   0.5   -    0.7   =    17.09
   1 0.75   4       3.7       -1.2       13.675
                    2.3                        
```

**Comment by philchalmers** [comment]
Here's an improved version to deal with missing label inputs. I like it better, and it seems to reflect your SAS version too:

```r
print_mat <- function(..., space = 1) {
    
    # get arguments
    args <- list(...)
    chars <- sapply(args, is.character)
    args[chars] <- lapply(args[chars], function(x) 
        paste0(rep(' ', space), x, rep(' ', space)))
    
    # vectors to matrix
    pick <- sapply(args, function(x) !is.matrix(x))
    args[pick] <- lapply(args[pick], as.matrix)
    
    nrows <- sapply(args, nrow)
    ncols <- sapply(args, ncol)
    
    mat <- matrix('', max(nrows), sum(ncols))
    nms <- rep('', sum(ncols))
    tmp <- names(args)
    Call <- as.character(match.call())[-1L]
    if(is.null(tmp)){
        tmp <- Call
    } else if(length(tmp[tmp != ""]) != sum(!chars)){
        tmp2 <- tmp
        tmp <- Call
        tmp[tmp2 != ""] <- tmp2[tmp2 != ""]
    }
    tmp[chars] <- ''
    nms[cumsum(ncols)] <- tmp
    
    for(i in 1L:max(nrows))
        mat[i, ] <- do.call(c, lapply(args, function(x) 
            if(nrow(x) >= i) as.character(x[i, ]) else rep('', ncol(x))))
    
    ret <- data.frame(mat, stringsAsFactors = FALSE)
    colnames(ret) <- nms
    print(ret, row.names=FALSE)
}

A <- matrix(c(2, 1, -1,
              -3, -1, 2,
              -2,  1, 2), 3, 3, byrow=TRUE)
x <- c(2, 3, -1)

print_mat(AA = A, "*", xx = x, '=', b = A %*% x) # no missing
       AA     xx       b
  2  1 -1  *   2  =    8
 -3 -1  2      3     -11
 -2  1  2     -1      -3

print_mat(A, "*", x, '=', A %*% x) # all missing
        A      x     A %*% x
  2  1 -1  *   2  =        8
 -3 -1  2      3         -11
 -2  1  2     -1          -3

print_mat(A, "*", x, '=', b = A %*% x) # mixed
        A      x       b
  2  1 -1  *   2  =    8
 -3 -1  2      3     -11
 -2  1  2     -1      -3
```

**Comment by friendly** [comment]
Thanks for reviving this; 
However, trying the  most recent code in a clean console give me something strange:

    > print_mat(A, "*", x, '=', A %*% x) # all missing
        structure(c("1", "-1", "1"), class = "AsIs")  A
      2                                            1 -1
     -3                                           -1  2
     -2                                            1  2
     structure(c(" * ", "", ""), class = "AsIs")  x
                                              *   2
                                                  3
                                                 -1
     structure(c(" = ", "", ""), class = "AsIs") A %*% x
                                              =        8
                                                     -11
                                                      -3
    >

Something to do with the colnames of the result?

**Comment by john-d-fox** [comment]
Hi Phil,

This looks very nice. I have one suggestion, best expressed in relation to your original message, to which I'm responding.

I find the inconsistent decimal formatting in matrix columns disconcerting. Compare, e.g., how R formats the matrix A in your second example:

> A
     [,1] [,2] [,3]
[1,]  0.5 3.00  2.8
[2,]  1.0 0.75  4.0

In many cases, it may even be preferable to format all of the cells of a matrix consistently. I can see cases where any of these approaches might run into scaling problems, so it may be sensible to provide options, with a default like column-consistent formatting.

Best,
 John

**Comment by philchalmers** [comment]
@friendly that's odd, I still get the same output as above. I'm not really sure why you are seeing the `structure` names come up. Do you have something added in `~.Rprofile` which causes this to occur? I tried it both in RStudio and a clean console R (v3.3.2) and both look okay.

@john-d-fox great point, I'll see if I can touch-up the formatting when decimals are present (and add the fractions support like in the rest of the package). Thanks for recommending this.

**Comment by friendly** [comment]
I'll try it on another computer.  I recently updated some packages, but got a bunch of warnings that I ignored.

**Comment by philchalmers** [comment]
No problem. Use the pointed to version [here](https://github.com/friendly/matlib/files/753418/print_mat.R.txt), which I think addresses John's observation more consistently. 


The digit-based example provides the following output now:

```r
> print_mat(A, "*", x, "-", y, "=", b)
              A       x        y          b
 0.50 3.00 2.80  *  0.5  -   0.7  =  17.090
 1.00 0.75 4.00     3.7     -1.2     13.675
                    2.3                    
> print_mat(A, "*", x, "-", y, "=", b, fractions=TRUE)
            A         x        y            b
 1/2   3 14/5  *    1/2  -  7/10  =  1709/100
   1 3/4    4     37/10     -6/5       547/40
                  23/10                   
```

There's not really much I can do about the spacing of fractions, but that's true everywhere in `matlib`.

**Comment by john-d-fox** [comment]
Hi Phil,

That looks much better to me.

Thanks,
 John

**Comment by friendly** [comment]
I just tried this on my work computer, also running R 3.2.5.  Under R Studio, I inserted `browser()` just before the final `print(ret, row.names=FALSE)`.  `nms` and `ret` look OK, but I still get that weird result when I print:

    > print_mat(AA = A, "*", xx = x, '=', b = A %*% x) # no missing
    Called from: print_mat(AA = A, "*", xx = x, "=", b = A %*% x)
    Browse[1]> 
    debug at #37: print(ret, row.names = FALSE)
    Browse[2]> nms
    Browse[2]> nms
    [1] ""   ""   "AA" ""   "xx" ""   "b" 
    [1] ""   ""   "AA" ""   "xx" ""   "b" 
    Browse[2]> str(ret)
    'data.frame':	3 obs. of  7 variables:
     $   : chr  "2" "-3" "-2"
     $   : chr  "1" "-1" "1"
     $ AA: chr  "-1" "2" "2"
     $   : chr  " * " "" ""
     $ xx: chr  "2" "3" "-1"
     $   : chr  " = " "" ""
     $ b : chr  "8" "-11" "-3"
    Browse[2]> str(ret)
    'data.frame':	3 obs. of  7 variables:
     $   : chr  "2" "-3" "-2"
     $   : chr  "1" "-1" "1"
     $ AA: chr  "-1" "2" "2"
     $   : chr  " * " "" ""
     $ xx: chr  "2" "3" "-1"
     $   : chr  " = " "" ""
     $ b : chr  "8" "-11" "-3"
    Browse[2]> ret
    Browse[2]> ret
         structure(c("1", "-1", "1"), class = "AsIs") AA structure(c(" * ", "", ""), class = "AsIs") xx
    1  2                                            1 -1                                          *   2
    2 -3                                           -1  2                                              3
    3 -2                                            1  2                                             -1
      structure(c(" = ", "", ""), class = "AsIs")   b
    1                                          =    8
    2                                             -11
    3                                              -3
         structure(c("1", "-1", "1"), class = "AsIs") AA structure(c(" * ", "", ""), class = "AsIs") xx
    1  2                                            1 -1                                          *   2
    2 -3                                           -1  2                                              3
    3 -2                                            1  2                                             -1
      structure(c(" = ", "", ""), class = "AsIs")   b
    1                                          =    8
    2                                             -11
    3                                              -3

**Comment by friendly** [comment]
Perhaps this problem is related to the following note that appears in the release notes for R 3.3.2:

* `format(<AsIs>)` looks more regular, also for non-character atomic matrices. 

If so, wouldn't this introduce a dependency on `R > 3.3.1` ?

**Comment by philchalmers** [comment]
Well, that's annoying. Confirmed on older 3.1.2 version. 

The fix is easy enough, just needs " " instead of "" spaces in `nms`. See [here](https://github.com/friendly/matlib/files/755209/print_mat.R.txt) for the updated version.

**Comment by friendly** [comment]
I just upgraded to R 3.3.2.  `print_mat` now works as expected, so the problem had to do with the formatting of class `AsIs`

**Comment by philchalmers** [comment]
Right, but the latest patch should work on all versions. So no need to force a version bump if this is added.
