### ISSUE TITLE
LU decomposition

### ISSUE THREAD

**Issue by philchalmers** [friendly/matlib#9]
```
Ax = b
LUx = b
LUx - b = 0
L(Ux - d) = 0
```

where `Ld = b`. Then do a simple forward-solve for `d`, and finally a simple back-solve for `x` given `d`. 

Any interest in this form of decomposition in the form of a function `LU()`? With all the ERO already defined it should be easy to do, and the solving of `d`/`x` could be made into a flag `solve = TRUE`. Otherwise, just the L and U matrices will be returned.

**Comment by john-d-fox** [comment]
Hi,

> -----Original Message-----
> From: Phil Chalmers [mailto:notifications@github.com]
> Sent: Tuesday, September 13, 2016 8:10 PM
> To: friendly/matlib matlib@noreply.github.com
> Subject: [friendly/matlib] LU decomposition (#9)
> 
> Ax = b
> LUx = b
> LUx - b = 0
> L(Ux - d) = 0
> 
> where Ld = b. Then do a simple back-solve for d, and finally a simple
> back-solve for x given d.
> 
> Any interest in this form of decomposition in the form of a function
> LU()? With all the ERO already defined it should be easy to do, and the
> solving of d/x could be made into a flag solve = TRUE. Otherwise, just
> the L and U matrices will be returned.

Sure. I defined cholesky(), eig(), QR(), and SVD(). We may a well have LU() too.

Best,
 John

**Comment by philchalmers** [comment]
Thanks, John. I've added a working version to the repo.

**Comment by friendly** [comment]
that's great! I updated `NEWS.md` and added `@return` to LU.

@john-d-fox : Is it useful to add `verbose=` here?

**Comment by john-d-fox** [comment]
Thanks for doing this.

**Comment by philchalmers** [comment]
@friendly there are only `nrow - 1` EROs in this approach, the rest is forward/backward substitutions. Could be weird to print because of the number of (y - dot product)/x operations, but is of course possible if there's interest. 

**Edit**: Scratch that, there are `sum((nrow-1):1)` ERO's, but the point about all the dot product math still stands.

**Comment by philchalmers** [comment]
In verbose mode, `LU()` now returns the following:

``` r
>   A <- matrix(c(2, 1, -1,
+                -3, -1, 2,
+                -2,  1, 2), 3, 3, byrow=TRUE)
>   b <- c(8, -11, -3)
>   LU(A, b, verbose=TRUE)

Initial equation:
 2*x1 + x2   - x3  =    8 
-3*x1 - x2 + 2*x3  =  -11 
-2*x1 + x2 + 2*x3  =   -3 

Lower triangle equation:
     x1              =    8 
-1.5*x1   + x2       =  -11 
    -x1 + 4*x2 + x3  =   -3 

Forward-solving operations:

  Equation: x1  =  8 
  Solution: x1 = 8/1 = 8

  Equation: -1.5*x1 + x2  =  -11 
  Substitution: -1.5*8 + x2 + 0*x3  =  -11 
  Solution: x2 = (-11 - -12) /1 = 1

  Equation: -x1 + 4*x2 + x3  =  -3 
  Substitution: -8 + 4*1 + x3  =  -3 
  Solution: x3 = (-3 - -4) /1 = 1

Intermediate solution: d = (8, 1, 1)

Upper triangle equation:
2*x1  + x2     - x3  =  8 
    0.5*x2 + 0.5*x3  =  1 
               - x3  =  1 

Back-solving operations:

  Equation:  - x3  =  1 
  Solution: x3 = 1/-1 = -1

  Equation: 0.5*x2 + 0.5*x3  =  1 
  Substitution: 0.5*x2 + 0.5*-1  =  1 
  Solution: x2 = (1 - -0.5) /0.5 = 3

  Equation: 2*x1 + x2 - x3  =  8 
  Substitution: 2*x1 + -1 - 3  =  8 
  Solution: x1 = (8 - 4) /2 = 2

Final solution: x = (2, 3, -1)
```

**Comment by friendly** [comment]
That is lovely!  Thanks for doing this.

**Comment by john-d-fox** [comment]
Yes, really nice! Thanks.

John
